# mamba env create -f environment.yml
name: heavyai-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - heavyai
  - heavydb
  - rbc
  - pandas
  - geopandas
  - contextily
  - jupyterlab
  - matplotlib
  - ipympl
