name: Notebooks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  eval-notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: echo "::set-output name=thisweek::$(/bin/date -u '+%Y%W')"
        shell: bash

      - name: Cache conda
        uses: actions/cache@v3
        id: conda_cache
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            conda-${{ env.CACHE_NUMBER }}-${{ steps.get-date.outputs.thisweek }}-${{ hashFiles('environment.yml') }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          channels: conda-forge
          channel-priority: true
          activate-environment: heavyai-env
          use-only-tar-bz2: true
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Update Conda Environment and install additional packages
        if: steps.conda_cache.outputs.cache-hit != 'true'
        run: |
          mamba env update -n heavyai-env -f environment.yml
          mamba install -c conda-forge heavydb nbval pytest

      - name: Start heavydb server
        run: |
          mkdir storage
          mamba run -n heavyai-env initheavy storage -f
          mamba run -n heavyai-env heavydb --version
          RUN_FLAGS="--enable-runtime-udfs --enable-table-functions --enable-dev-table-functions --enable-udf-registration-for-all-users"
          echo ${RUN_FLAGS}
          mamba run -n heavyai-env heavydb $RUN_FLAGS &> heavydb-output.txt &
          sleep 10

      - name: Execute pytest
        run: |
          pytest -v -rs --nbval-lax ./
          killall heavydb
          cat heavydb-output.txt
